export enum ColorsEnum {
    transparent = "#00000000",
    white = "#fff",
    smokeWhite = "#eee",
    whiteBlue = "#ecf0f5",
    black = "#333",
    gray = "#aaa",
    dimGray = "#888",
    lightGray = "#ccc",
    smokeGray = "#374850",
    slateGray = "#2c3b41",
    darkSlateGray = "#222d32",
    darkGray = "#282c34",
    blue = "#2196c4",
    lightBlue = "#00c0ef",
    skyBlue = "#91c2ce",
    cornflowerBlue = "#729aca",
    green = "#5cb85c",
    seaGreen = "#00a65a",
    red = "#d9534f",
    orange = "#f0ad4e",
    darkOrange = "#f39c12",
    violet = "#8064a2",
    yellow = "#FFFF00",
    pink = "#FFB6C1",
    vipGold = "#ffcf40",
    deepSkyBlue = "#00BFFF"
  }
  
  export const colors = {
    all: {
      transparent: ColorsEnum.transparent,
      white: ColorsEnum.white,
      smokeWhite: ColorsEnum.smokeWhite,
      whiteBlue: ColorsEnum.whiteBlue,
      black: ColorsEnum.black,
      gray: ColorsEnum.gray,
      dimGray: ColorsEnum.dimGray,
      lightGray: ColorsEnum.lightGray,
      smokeGray: ColorsEnum.smokeGray,
      slateGray: ColorsEnum.slateGray,
      darkSlateGray: ColorsEnum.darkSlateGray,
      darkGray: ColorsEnum.darkGray,
      blue: ColorsEnum.blue,
      lightBlue: ColorsEnum.lightBlue,
      skyBlue: ColorsEnum.skyBlue,
      cornflowerBlue: ColorsEnum.cornflowerBlue,
      green: ColorsEnum.green,
      seaGreen: ColorsEnum.seaGreen,
      red: ColorsEnum.red,
      orange: ColorsEnum.orange,
      darkOrange: ColorsEnum.darkOrange,
      violet: ColorsEnum.violet,
      yellow: ColorsEnum.yellow,
      pink: ColorsEnum.pink,
      vipGold: ColorsEnum.vipGold,
      deepSkyBlue: ColorsEnum.deepSkyBlue
    }
  };
  